### ISSUE TITLE
do not use generic names for receiver variable, like "this"

### ISSUE THREAD

**Issue by h12w** [stealthly/siesta#10]
Reference:
* https://github.com/golang/go/wiki/CodeReviewComments#receiver-names
* https://github.com/hailiang/gosweep

**Comment by serejja** [comment]
This should already be fixed in https://github.com/stealthly/siesta/tree/refactor-and-lint
All these checks should pass there.
Not merged yet though. Will probably be merged together with producer.

**Comment by serejja** [comment]
One more note for why it's not merged yet - this branch contains some breaking changes because of Kafka naming conventions so we decided to wait a little bit before merging that.
Thanks
