### ISSUE TITLE
Producer API memory leak

### ISSUE THREAD

**Issue by LLParse** [stealthly/siesta#20]
The producer API appears to be leaking memory. Iterative producing causes memory consumption to steadily rise. For reproduction, use the *TestProducerSend1000* method in *kafka_producer_test.go*. You may also increase the loop size to get a better sampling.

Take a look at the memory profile of this test case:
```bash
go test -c
./siesta.test -test.memprofile=mem.profile -test.bench=TestProducerSend1000
go tool pprof siesta.test mem.profile
(pprof) top
```

**Comment by serejja** [comment]
I think this happens because record metadata channel is not being read. Will recheck this.

**Comment by LLParse** [comment]
Yes you are correct, I was not reading the channel and it was filling up. I'm curious why it even worked when RequiredAcks = 1, when I turned off RequiredAcks the chan filled up and I hit deadlock.

**Comment by serejja** [comment]
RequiredAcks does not affect record metadata channel. For now if you have RequiredAcks = 1 the record metadata will be sent once the response is received and if RequiredAcks = 0 the record metadata will be sent immediately - [https://github.com/stealthly/siesta/blob/master/network_client.go#L53-L65](https://github.com/stealthly/siesta/blob/master/network_client.go#L53-L65)

**Comment by serejja** [comment]
Not sure, maybe we should change the way it behaves but JVM producer does exactly this.
