### ISSUE TITLE
Siesta cannot be used as a producer

### ISSUE THREAD

**Issue by h12w** [stealthly/siesta#9]
syncSendAndReceive is unexported, though ProduceRequest is defined, there is no method to send them out. So basically Siesta cannot be used as a producer. Is it designed purposely like this?

**Comment by serejja** [comment]
@hailiang producer is being actively developed here: https://github.com/stealthly/siesta/tree/producer

**Comment by hailiang** [comment]
Thanks. When will the producer code merged to master branch?

**Comment by yanzay** [comment]
Producer is nearly finished, but it will take some time to test it properly, maybe in a couple days.

**Comment by hailiang** [comment]
I checked the code on producer branch, but a "Send" method is still missing in the Connector type.

**Comment by yanzay** [comment]
It's not in repo yet, in active development right now.
